# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateAgent_SIR <- function(current_state, prob) {
    .Call(`_Catalyst_updateAgent_SIR`, current_state, prob)
}

AMTime_SIR <- function(A, prob_inf, prob_rec) {
    .Call(`_Catalyst_AMTime_SIR`, A, prob_inf, prob_rec)
}

get_n_nbr_inf <- function(nbr_list, inf_inds) {
    .Call(`_Catalyst_get_n_nbr_inf`, nbr_list, inf_inds)
}

updateNeighbors <- function(orig_nbrs, preventions_nbrs, preventions_inds) {
    .Call(`_Catalyst_updateNeighbors`, orig_nbrs, preventions_nbrs, preventions_inds)
}

removeNeighbors <- function(orig_nbrs, preventions_nbrs, inf_inds, preventions_inds) {
    .Call(`_Catalyst_removeNeighbors`, orig_nbrs, preventions_nbrs, inf_inds, preventions_inds)
}

rcppRev <- function(x) {
    .Call(`_Catalyst_rcppRev`, x)
}

removeClosureNbrs <- function(nbr_list, cat_inds) {
    .Call(`_Catalyst_removeClosureNbrs`, nbr_list, cat_inds)
}

addClosureNbrs <- function(nbr_list, cat_inds) {
    .Call(`_Catalyst_addClosureNbrs`, nbr_list, cat_inds)
}

deg_to_rad_rcpp <- function(degree) {
    .Call(`_Catalyst_deg_to_rad_rcpp`, degree)
}

dist_haversine_rcpp <- function(xlon, xlat, ylon, ylat) {
    .Call(`_Catalyst_dist_haversine_rcpp`, xlon, xlat, ylon, ylat)
}

nbrsByDist <- function(M, thresh, max_nbrs) {
    .Call(`_Catalyst_nbrsByDist`, M, thresh, max_nbrs)
}

findIfSus <- function(A0, IMax, T) {
    .Call(`_Catalyst_findIfSus`, A0, IMax, T)
}

makeStateVec <- function(A0, state) {
    .Call(`_Catalyst_makeStateVec`, A0, state)
}

whichState <- function(x, state) {
    .Call(`_Catalyst_whichState`, x, state)
}

countIntersect <- function(infVec, nbrOfSusInds) {
    .Call(`_Catalyst_countIntersect`, infVec, nbrOfSusInds)
}

updateStateByInds <- function(vec, inds) {
    .Call(`_Catalyst_updateStateByInds`, vec, inds)
}

updateStateVec <- function(vec1, vec2) {
    .Call(`_Catalyst_updateStateVec`, vec1, vec2)
}

AMSIR_sus_inner <- function(ll, T, A0, nbrList, beta, gamma) {
    .Call(`_Catalyst_AMSIR_sus_inner`, ll, T, A0, nbrList, beta, gamma)
}

AMSIR <- function(L, T, A0, nbrList, beta, gamma) {
    .Call(`_Catalyst_AMSIR`, L, T, A0, nbrList, beta, gamma)
}

rcpp_hello <- function() {
    .Call(`_Catalyst_rcpp_hello`)
}

sirLoopGroups <- function(x, beta_vec, gamma_vec, T, prob_type) {
    .Call(`_Catalyst_sirLoopGroups`, x, beta_vec, gamma_vec, T, prob_type)
}

totalX <- function(X) {
    .Call(`_Catalyst_totalX`, X)
}

sirLoop <- function(x, beta, gamma, T, prob_type) {
    .Call(`_Catalyst_sirLoop`, x, beta, gamma, T, prob_type)
}

initializeNeighbors <- function(env_mat) {
    .Call(`_Catalyst_initializeNeighbors`, env_mat)
}

loglike_SIR_CM <- function(T, pt, gamma, X, N) {
    .Call(`_Catalyst_loglike_SIR_CM`, T, pt, gamma, X, N)
}

UtoA_SIR <- function(U, Tmax) {
    .Call(`_Catalyst_UtoA_SIR`, U, Tmax)
}

AtoU_SIR <- function(A) {
    .Call(`_Catalyst_AtoU_SIR`, A)
}

AtoX <- function(A, K) {
    .Call(`_Catalyst_AtoX`, A, K)
}

extractRowA <- function(A, t) {
    .Call(`_Catalyst_extractRowA`, A, t)
}

extractColA <- function(A, n) {
    .Call(`_Catalyst_extractColA`, A, n)
}

UtoX_SIR <- function(U, T) {
    .Call(`_Catalyst_UtoX_SIR`, U, T)
}

