# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateAgent_SIR <- function(current_state, prob) {
    .Call(`_Catalyst_updateAgent_SIR`, current_state, prob)
}

AMTime_SIR <- function(A, prob_inf, prob_rec) {
    .Call(`_Catalyst_AMTime_SIR`, A, prob_inf, prob_rec)
}

get_n_nbr_inf <- function(nbr_list, inf_inds) {
    .Call(`_Catalyst_get_n_nbr_inf`, nbr_list, inf_inds)
}

rcpp_hello <- function() {
    .Call(`_Catalyst_rcpp_hello`)
}

sirLoopGroups <- function(x, beta_vec, gamma_vec, T, prob_type) {
    .Call(`_Catalyst_sirLoopGroups`, x, beta_vec, gamma_vec, T, prob_type)
}

sirLoop <- function(x, beta, gamma, T, prob_type) {
    .Call(`_Catalyst_sirLoop`, x, beta, gamma, T, prob_type)
}

initializeNeighbors <- function(env_mat) {
    .Call(`_Catalyst_initializeNeighbors`, env_mat)
}

loglike_SIR_CM <- function(T, pt, gamma, X, N) {
    .Call(`_Catalyst_loglike_SIR_CM`, T, pt, gamma, X, N)
}

UtoA_SIR <- function(U, Tmax) {
    .Call(`_Catalyst_UtoA_SIR`, U, Tmax)
}

AtoU_SIR <- function(A) {
    .Call(`_Catalyst_AtoU_SIR`, A)
}

AtoX <- function(A, K) {
    .Call(`_Catalyst_AtoX`, A, K)
}

extractRowA <- function(A, t) {
    .Call(`_Catalyst_extractRowA`, A, t)
}

extractColA <- function(A, n) {
    .Call(`_Catalyst_extractColA`, A, n)
}

UtoX_SIR <- function(U, T) {
    .Call(`_Catalyst_UtoX_SIR`, U, T)
}

